-- DRAFT ONLY - DO NOT APPLY.
-- Phase 5AK.2 review artifact for future Telegram webhook session lookup work.
-- This file is intentionally comment-only and contains no executable SQL.
-- Do not remove comment prefixes or run adapted SQL without explicit approval.

-- Purpose
-- - Capture the intended SQL boundary for Telegram webhook secret lookup.
-- - Keep Telegram chat authorization outside this schema slice until its
--   identity matching and role/scope rules are separately approved.
-- - Keep production unchanged until schema, RLS, grants, verifier, and rollout
--   approvals are explicit.
-- - Give reviewers stable object names and privilege expectations before any
--   executable SQL is written.

-- Hard boundaries
-- - No table, index, policy, grant, trigger, or function is created by this
--   draft.
-- - No Supabase Vault secret is created, read, updated, or revoked by this
--   draft.
-- - No raw BotFather token or raw webhook secret is stored by this draft.
-- - No Edge Function, frontend, Telegram API, webhook registration, command
--   parser, or reply sender behavior is wired by this draft.
-- - This draft must not be applied in Supabase.

-- Required approvals before converting this draft into executable SQL
-- - Confirm the session-lookup-only rollout boundary.
-- - Confirm exact table name, column names, constraints, and indexes.
-- - Confirm webhook secret hash algorithm and secret reference format.
-- - Confirm whether hash generation happens only in Edge Functions or through
--   an approved server-side RPC.
-- - Confirm final RLS/grant statements.
-- - Extend the verifier to check RLS state, exact columns and constraints,
--   partial unique indexes, security-definer state, and restricted search path.
-- - Confirm verifier expected outputs and a rollback artifact before applying.
-- - Run the verifier before and after any approved migration.

-- Objects in the current session-lookup slice
-- - Webhook secret table: public.telegram_webhook_secrets
-- - Webhook session lookup RPC: public.resolve_telegram_webhook_session(text)

-- Explicitly deferred objects
-- - Chat authorization table: public.telegram_chat_authorizations
-- - Chat policy lookup RPC: public.resolve_telegram_chat_authorization(uuid,text,text,text)
-- - No DDL, RPC, grant, verifier expectation, or rollout approval for these
--   deferred objects belongs to the current slice.

-- Proposed webhook secret table shape
-- - webhook_secret_ref text primary key
-- - webhook_secret_hash text not null
-- - telegram_session_id uuid not null references public.telegram_sessions(id) on delete cascade
-- - created_at timestamptz not null default now()
-- - revoked_at timestamptz null
-- - agent_id is intentionally not stored here; the session is the single source
--   of truth for agent ownership and prevents session/agent drift.

-- Commented DDL sketch
-- - Future executable SQL must fail if this table already exists. Do not use
--   create table if not exists because it can silently accept a wrong shape.
-- create table public.telegram_webhook_secrets (
--   webhook_secret_ref text primary key,
--   webhook_secret_hash text not null,
--   telegram_session_id uuid not null references public.telegram_sessions(id) on delete cascade,
--   created_at timestamptz not null default now(),
--   revoked_at timestamptz null,
--   check (length(btrim(webhook_secret_ref)) > 0),
--   check (length(btrim(webhook_secret_hash)) > 0)
-- );

-- Index intent
-- - One active webhook secret per Telegram session.
-- - Fast lookup by webhook_secret_hash.
-- - The hash should not be reversible and must not be exposed to browser roles.
-- create unique index telegram_webhook_secrets_active_session_key
--   on public.telegram_webhook_secrets (telegram_session_id)
--   where revoked_at is null;
-- create unique index telegram_webhook_secrets_active_hash_key
--   on public.telegram_webhook_secrets (webhook_secret_hash)
--   where revoked_at is null;

-- Browser access boundary
-- - anon and authenticated browser clients must not read or write the private
--   webhook secret table.
-- - service_role should be the only role with direct table access.
-- - Public views must not include webhook_secret_ref, webhook_secret_hash,
--   owner_user_id, workspace_id, raw Telegram payloads, or raw DB errors.

-- Commented RLS/grant sketch
-- alter table public.telegram_webhook_secrets enable row level security;
-- revoke all on public.telegram_webhook_secrets from public;
-- revoke all on public.telegram_webhook_secrets from anon;
-- revoke all on public.telegram_webhook_secrets from authenticated;
-- grant select, insert, update on public.telegram_webhook_secrets to service_role;

-- Webhook session lookup RPC intent
-- - Input is a webhook secret hash or approved opaque reference only.
-- - The RPC resolves the secret to exactly one active Telegram session.
-- - The RPC joins telegram_sessions -> agent_instances -> workspaces.
-- - The RPC returns only internal fields needed by telegram-webhook.
-- - The RPC must not return webhook_secret_ref, webhook_secret_hash,
--   token_secret_ref, raw Telegram payloads, raw DB errors, or raw secrets.

-- Commented lookup function sketch
-- - Future executable SQL must fail if this RPC already exists. Do not use
--   create or replace function until a separately reviewed forward-fix is
--   required.
-- create function public.resolve_telegram_webhook_session(
--   p_webhook_secret_hash text
-- ) returns table (
--   session_id uuid,
--   agent_id uuid,
--   workspace_id uuid,
--   owner_user_id uuid,
--   bot_handle text,
--   webhook_status text
-- )
-- language sql
-- stable
-- security definer
-- set search_path = pg_catalog, public, pg_temp
-- as $$
--   select
--     sessions.id as session_id,
--     sessions.agent_id,
--     agents.workspace_id,
--     workspaces.owner_user_id,
--     sessions.bot_handle,
--     sessions.webhook_status
--   from public.telegram_webhook_secrets secrets
--   join public.telegram_sessions sessions
--     on sessions.id = secrets.telegram_session_id
--   join public.agent_instances agents
--     on agents.id = sessions.agent_id
--   join public.workspaces workspaces
--     on workspaces.id = agents.workspace_id
--   where secrets.webhook_secret_hash = btrim(p_webhook_secret_hash)
--     and secrets.revoked_at is null
--     and sessions.webhook_status = 'active'
--   limit 2;
-- $$;

-- Deferred chat authorization boundary
-- - Do not create telegram_chat_authorizations or its lookup RPC in this slice.
-- - A later design must define whether user and chat identifiers are matched as
--   a pair, independently, or through explicit identity types.
-- - A later design must enforce an approved role/scope matrix so a member
--   cannot silently receive write or approval authority.
-- - Unknown chats must remain safe denial/no-op.

-- Commented function privilege sketch
-- - PostgreSQL may grant execute on functions to PUBLIC by default.
-- - Future executable SQL must revoke from public before granting backend-only
--   access.
-- revoke execute on function public.resolve_telegram_webhook_session(text) from public;
-- revoke execute on function public.resolve_telegram_webhook_session(text) from anon;
-- revoke execute on function public.resolve_telegram_webhook_session(text) from authenticated;
-- grant execute on function public.resolve_telegram_webhook_session(text) to service_role;

-- Expected verifier checks after an approved apply
-- - telegram_webhook_secrets table exists.
-- - The table has exactly the approved columns and no redundant agent_id.
-- - RLS is enabled.
-- - Both approved partial unique indexes exist with the expected predicates.
-- - public, anon, and authenticated cannot select, insert, update, or delete
--   the private table.
-- - service_role has only the required direct table privileges.
-- - resolve_telegram_webhook_session exists.
-- - The RPC is stable, security definer, and has the approved restricted
--   search path.
-- - public, anon, and authenticated cannot execute the lookup RPC.
-- - service_role can execute the lookup RPC.
-- - telegram_session_summaries still excludes token_secret_ref, owner_user_id,
--   workspace_id, webhook secret refs/hashes, and raw Telegram payloads.
-- - authenticated still cannot broad-select telegram_sessions.

-- Required preflight before an approved apply
-- - Confirm telegram_webhook_secrets and resolve_telegram_webhook_session(text)
--   do not already exist. Abort instead of adapting them in place.
-- - Capture the verifier baseline before apply.
-- - Confirm webhook registration, webhook lookup, command processing, Edge
--   Function deployment, and all related runtime gates remain disabled.
-- - Review the exact forward SQL and exact rollback SQL together.
-- - Apply only inside a transaction and run the verifier immediately after
--   commit before any runtime wiring.

-- Rollback boundary
-- - Prefer transaction rollback for any apply-time failure.
-- - Post-commit removal is allowed only while runtime remains disabled and the
--   private table contains no required production data.
-- - Revoke execute from service_role before dropping the RPC.
-- - Drop the exact RPC signature before dropping the table.
-- - Do not use CASCADE.
-- - If data exists or runtime has been enabled, use a reviewed forward fix.

-- Future implementation order after approval
-- - Extend verifier coverage for the session-lookup slice.
-- - Convert only the session-lookup slice into reviewed executable SQL.
-- - Prepare and review the non-CASCADE rollback artifact.
-- - Apply only in Supabase after explicit schema/RLS/grant approval.
-- - Run verifier and capture results before and after apply.
-- - Update generated/local database types after schema approval.
-- - Add Edge Function DB adapters behind mocked tests first.
-- - Wire telegram-webhook lookup only after adapter and verification-order tests
--   pass.
-- - Keep command parsing and reply sending separate later phases.

-- Still blocked until separately approved
-- - Executable SQL.
-- - schema.sql or verifier SQL edits.
-- - Supabase SQL apply.
-- - Real webhook secret creation or hashing.
-- - Real session lookup wiring.
-- - Chat authorization table or RPC implementation.
-- - Telegram update parsing.
-- - Telegram command processing.
-- - Telegram reply sender.
-- - Edge Function deploy.
-- - Netlify unlock or production publish.
